name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote commands over SSH
        uses: appleboy/ssh-action@master
        with:
          host: 13.53.44.32
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/projects/myproject3/deploy3   # Replace with your app path
            git pull origin main
            npm install
            npm run build
            pm2 restart next-app || pm2 start npm --name "next-app" -- start
